title: "Forus Documentation"
description: Forus docs

# leave trailing slash off
url: https://docs.forus.io
foundationurl: https://about.forus.io

# bump if alterting styles or js
version: 27

defaults:
  - scope:
      type: ""
    values:
      layout: "default"

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

markdown: kramdown

highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
